version: "3"

services:
  nginx:
    image: nginx
    networks:
      - webgateway
    volumes:
      - $PWD/www:/usr/share/nginx/html:ro
    restart: on-failure
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.cv-snt.rule=Host(`snt.nayzbysodium.com`)
      - traefik.http.routers.cv-snt.entrypoints=websecure
      - traefik.http.routers.cv-snt.service=cv-snt
      - traefik.http.services.cv-snt.loadbalancer.server.port=80
      - traefik.http.routers.cv-snt.tls.certresolver=production
    
networks:
  webgateway:
    external: true
    name: webgateway
